// Generated by CoffeeScript 1.6.3
(function() {
  var HotConfig, configs, fs, updateConfig;

  configs = {};

  fs = require('fs');

  HotConfig = function(key) {
    if (!configs[key]) {
      configs[key] = require(HotConfig.prefix + key + ".json");
    }
    return configs[key];
  };

  updateConfig = function(key, config) {
    return fs.readFile(HotConfig.prefix + key + ".json", 'utf-8', function(error, content) {
      var e, obj;
      try {
        obj = JSON.parse(content);
        if (!obj.version) {
          throw new Error('must have field "version" in config file');
        }
        if (obj.version !== configs[key].version) {
          return configs[key] = obj;
        } else {
          return obj = null;
        }
      } catch (_error) {
        e = _error;
        return console.log('hotconfig parse error:' + key);
      }
    });
  };

  setInterval(function() {
    var config, key, _results;
    _results = [];
    for (key in configs) {
      config = configs[key];
      _results.push(updateConfig(key, config));
    }
    return _results;
  }, 1000);

  HotConfig.prefix = __dirname;

  module.exports = HotConfig;

}).call(this);
